### ISSUE TITLE
AVANTES: function 'AVS_ActivateConn' not found

### ISSUE THREAD

**Issue by Saldenisov** [MSLNZ/msl-equipment#9] opened 2023-11-22 10:35 UTC
When using version 0.2.0 the code gives this error `function 'AVS_ActivateConn' not found`, python version = 3.9.18. 
When running with version 0.1.0 the codes executes with python version = 3.8.12.
Once I updated version 0.1.0 to 0.2.0 and then went back to 0.1.0 with python 3.8, nothing works:(
Can you please solve this issue?

**Comment by jborbely** [comment] 2023-11-22 21:04
I think the issue is that you also changed the version of the AvaSpec DLL that you are using. Did you change the DLL?

The version of the DLL that was used to write the Python wrapper code was AvaSpec version 9.7.0.0 (January 2018). The Avantes software developers probably removed the ``AVS_ActivateConn`` function from the version of the DLL that you are now using.

If you use an older DLL that may solve this issue.

Alternatively, if you want to use the newer DLL, you need to comment out (or delete) [lines 610 and 611](https://github.com/MSLNZ/msl-equipment/blob/a71b4486f169bb164d58d61cb1bf7616787a2cd9/msl/equipment/resources/avantes/avaspec.py#L610-L611) in your ``..\site-packages\msl\equipment\resources\avantes\avaspec.py`` file. That should fix your specific error; however, more errors may occur because the DLL is different and more DLL functions may have been removed or the DLL function signatures may have been modified.

Please let me know which ``'AVS_*'`` functions you needed to comment out (delete) in your ``avaspec.py`` file to no longer get an ``AttributeError: function 'AVS_*' not found`` when you connect to your device. I can then see if these missing DLL functions would cause an issue in the wrapper code and update the wrapper code accordingly. If you are able to share the DLL you are using, that would be helpful.

**Comment by Saldenisov** [comment] 2023-12-07 09:52
Hi @jborbely 

I commented these lines in avaspec.py

```
'AVS_Heartbeat'
'AVS_GetOemParameter'
'AVS_SetOemParameter'
'AVS_ActivateConnCb'
```

AVANTES does not respond on email. Seems to be, that I need to call them.

here is the [link](https://we.tl/t-K1p12awv61) to DLL.

**Comment by jborbely** [comment] 2023-12-08 02:33
The version of your DLL is 9.4.0.1 (older than 9.7.0.0), which means that those functions were not yet written.

I have pushed a fix for this issue.

**Closed as completed** 2023-12-08 02:34 UTC
